name: Metrics

on:
  schedule: [{cron: "0 * * * *"}]  # 每天 00:00 UTC 自动执行
  workflow_dispatch:             # 允许手动触发

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          
          # Options
          user: LaoZhuJackson
          template: classic
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_followup: yes
          plugin_traffic: yes
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_gists: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 4
